version = 0.1
[default.deploy.parameters]
stack_name = "sam-bookapp"
resolve_s3 = true
s3_prefix = "sam-bookapp"
region = "us-east-1"
profile = "aws-alfio-hotmail"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
