AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: SAM template for Book Inventory Management with API Gateway, Lambda, and DynamoDB

Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: !Ref BooksTable

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sam-bookapp-bucket

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BooksTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GetBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/GetBook
      Handler: getBook.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
      Events:
        GetBookApi:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: GET

  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/DeleteBook
      Handler: deleteBook.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Events:
        DeleteBookApi:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: DELETE

  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/CreateBook
      Handler: createBook.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Events:
        CreateBookApi:
          Type: Api
          Properties:
            Path: /books
            Method: POST

  UpdateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/UpdateBook
      Handler: updateBook.handler
      Runtime: nodejs20.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Events:
        UpdateBookApi:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: PUT

Outputs:
  GetBookApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/{id}"
    Description: "Endpoint for getting a book by ID"

  CreateBookApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books"
    Description: "Endpoint for creating a new book"

  UpdateBookApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/{id}"
    Description: "Endpoint for updating a book by ID"
